export const state = {
  viewer: null,
  /** @type {"life" | "memory" | null} */
  appMode: null,
  allMemoryPhotos: [],
  filteredMemoryPhotos: [],
  /** 過去写真シートの読込が完了したか（成功・失敗いずれでも true） */
  memoryDataLoaded: false,
  memoryDataSource: null,
  google3dTileset: null,
  fallbackBuildings: null,
  pointCloudViewer: null,
  pointCloudTileset: null,
  pointCloudPreviewViewer: null,
  pointCloudPreviewTileset: null,
  pointCloudPreviewLoadGeneration: 0,
  pointCloudModalLoadGeneration: 0,
  currentPointCloudAssetId: null,
  currentPointCloudTitle: "",
  cachedTileset: null,
  cachedTilesetAssetId: null,
  cachedTilesetPromise: null,
  pointCloudScratchPos: null,
  pointCloudScratchA: null,
  pointCloudScratchB: null,
  pointCloudScratchHpr: null,
  pointCloudScratchEnu: null,
  allPins: [],
  filteredPins: [],
  pinHeightCache: new Map(),
  categoryOptions: [],
  roleOptions: [],
  roleColors: {},
  selectedCategories: new Set(),
  selectedRoles: new Set(),
  selectedYear: new Date().getFullYear(),
  yearSliderMin: 1930,
  yearSliderMax: new Date().getFullYear(),
  usesGoogle3DTiles: true,
  /** Google 3D Tiles が視点上に1枚でも描画されたか（地球を隠してよいか） */
  google3dTilesPainted: false,
  defaultImageryLayer: null,
  basePaleLayer: null,
  mapGeometryReady: false,
  historicalImageryLayer: null,
  historicalMapActive: false,
  historicalCameraSaved: null,
  historicalCameraClamp: null,
  selectedPinEntity: null,
  savedCameraView: null,
  isCameraZoomed: false
};
