export const state = {
  viewer: null,
  google3dTileset: null,
  fallbackBuildings: null,
  pointCloudViewer: null,
  pointCloudTileset: null,
  pointCloudPreviewViewer: null,
  pointCloudPreviewTileset: null,
  pointCloudPreviewLoadGeneration: 0,
  pointCloudModalLoadGeneration: 0,
  currentPointCloudAssetId: null,
  currentPointCloudTitle: "",
  cachedTileset: null,
  cachedTilesetAssetId: null,
  cachedTilesetPromise: null,
  pointCloudScratchPos: null,
  pointCloudScratchA: null,
  pointCloudScratchB: null,
  allPins: [],
  filteredPins: [],
  pinHeightCache: new Map(),
  categoryOptions: [],
  activityOptions: [],
  activityColors: {},
  selectedCategories: new Set(),
  selectedActivities: new Set(),
  selectedYear: null,
  yearSliderMin: 1930,
  yearSliderMax: new Date().getFullYear(),
  usesGoogle3DTiles: true,
  defaultImageryLayer: null,
  basePaleLayer: null,
  historicalImageryLayer: null,
  historicalMapActive: false,
  historicalCameraSaved: null,
  historicalCameraClamp: null,
  selectedPinEntity: null,
  savedCameraView: null,
  isCameraZoomed: false
};
